apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: photoprism
  namespace: rndir
spec:
  selector:
    matchLabels:
      app: photoprism
  serviceName: photoprism
  replicas: 1
  template:
    metadata:
      labels:
        app: photoprism
    spec:
      containers:
      - name: photoprism
        image: photoprism/photoprism:latest
        ports:
        - containerPort: 80
          name: http
        envFrom:
        - secretRef:
            name: photoprism-secrets
            optional: false
        - configMapRef:
           name: photoprism-configmap
        volumeMounts:
        - mountPath: "/nfs"
          name: photoprism-nfs
      volumes:
      - name: photoprism-nfs
        persistentVolumeClaim:
          claimName: photoprism-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: photoprism
  namespace: rndir 
  labels:
    app: photoprism
spec:
  selector:
    app: photoprism
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-pvc
  namespace: rndir
  labels:
    app: photoprism
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
