apiVersion: cert-manager.io/v1
kind: Issuer 
metadata:
  name: letsencrypt-staging
  namespace: rndir
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@rndir.cc
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        cloudDNS:
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: key.json
          project: rndir-b1367ea6
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: rndir
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@rndir.cc
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        cloudDNS:
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: key.json
          project: rndir-b1367ea6
