apiVersion: v1
kind: ServiceAccount
metadata:
  name: pods-killer
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pods-killer
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]      
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pods-killer
  namespace: default
subjects:
  - kind: ServiceAccount
    name: pods-killer
    namespace: default 
roleRef:
  kind: ClusterRole
  name: pods-killer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pods-killer
  namespace: default
spec:
  schedule: "*/30 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          name: pods-killer
          namespace: default
        spec:
          serviceAccountName: pods-killer
          restartPolicy: Never
          containers:
          - name: pods-killer
            image: bitnami/kubectl
            command:
              - "/bin/sh"
            args:
              - "-c"
              - "kubectl get pods -A | grep Shutdown | awk '{print $1, $2}' | xargs -r kubectl delete pods -n"
