apiVersion: v1
kind: ConfigMap
metadata:
  name: photoprism-configmap
  namespace: rndir
data:
  PHOTOPRISM_SITE_URL: "https://photos.rndir.cc"
  PHOTOPRISM_SITE_TITLE: "PhotoPrism"
  PHOTOPRISM_SITE_CAPTION: "Browse Your Life"
  PHOTOPRISM_SITE_DESCRIPTION: "Open-Source Photo Management"
  PHOTOPRISM_SITE_AUTHOR: "Randy Cahyana"
  PHOTOPRISM_DEBUG: "true"
  PHOTOPRISM_READONLY: "false"
  PHOTOPRISM_PUBLIC: "true"
  PHOTOPRISM_EXPERIMENTAL: "true"
  PHOTOPRISM_SERVER_MODE: "debug"
  PHOTOPRISM_HTTP_HOST: "0.0.0.0"
  PHOTOPRISM_HTTP_PORT: "80"
  PHOTOPRISM_HTTP_COMPRESSION: "gzip"     # Improves transfer speed and bandwidth utilization (none or gzip)
  PHOTOPRISM_DATABASE_DRIVER: "postgres"
  PHOTOPRISM_DATABASE_SERVER: "rndir-storage-postgresql.default.svc.cluster.local:5432"
  PHOTOPRISM_DATABASE_NAME: "photoprism"
  PHOTOPRISM_DATABASE_USER: "postgres"
  PHOTOPRISM_DATABASE_PASSWORD: "photoprism"
  PHOTOPRISM_TEST_DRIVER: "sqlite"
  PHOTOPRISM_TEST_DSN: ".test.db"
  PHOTOPRISM_ASSETS_PATH: "/photoprism/assets"
  PHOTOPRISM_STORAGE_PATH: "/photoprism/assets/photos"
  PHOTOPRISM_ORIGINALS_PATH: "/photoprism/assets/photos/originals"
  PHOTOPRISM_IMPORT_PATH: "/photoprism/assets/photos/import"
  PHOTOPRISM_DISABLE_BACKUPS: "true"      # Don't backup photo and album metadata to YAML files
  PHOTOPRISM_DISABLE_WEBDAV: "true"       # Disables built-in WebDAV server
  PHOTOPRISM_DISABLE_SETTINGS: "false"    # Disables Settings in Web UI
  PHOTOPRISM_DISABLE_PLACES: "true"       # Disables reverse geocoding and maps
  PHOTOPRISM_DISABLE_EXIFTOOL: "false"    # Don't create ExifTool JSON files for improved metadata extraction
  PHOTOPRISM_DISABLE_TENSORFLOW: "false"  # Don't use TensorFlow for image classification
  PHOTOPRISM_DETECT_NSFW: "false"         # Flag photos as private that MAY be offensive (requires TensorFlow)
  PHOTOPRISM_UPLOAD_NSFW: "false"         # Allows uploads that may be offensive
  PHOTOPRISM_DARKTABLE_PRESETS: "false"   # Enables Darktable presets and disables concurrent RAW conversion
  PHOTOPRISM_THUMB_FILTER: "lanczos"      # Resample filter, best to worst: blackman, lanczos, cubic, linear
  PHOTOPRISM_THUMB_UNCACHED: "true"       # Enables on-demand thumbnail rendering (high memory and cpu usage)
  PHOTOPRISM_THUMB_SIZE: "2048"           # Pre-rendered thumbnail size limit (default 2048, min 720, max 7680)
  # PHOTOPRISM_THUMB_SIZE: 4096           # Retina 4K, DCI 4K (requires more storage); 7680 for 8K Ultra HD
  PHOTOPRISM_THUMB_SIZE_UNCACHED: "7680"  # On-demand rendering size limit (default 7680, min 720, max 7680)
  PHOTOPRISM_JPEG_SIZE: "7680"            # Size limit for converted image files in pixels (720-30000)
  PHOTOPRISM_JPEG_QUALITY: "92"           # Set to 95 for high-quality thumbnails (25-100)
