apiVersion: apps/v1
kind: Deployment
metadata:
  name: site
  namespace: rndir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site
  template:
    spec:
      containers:
      - image: ko://rndir.cc
        imagePullPolicy: IfNotPresent
        name: site
        envFrom:
        - configMapRef:
           name: site-configmap
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 30m
            memory: 50Mi
    metadata:
      labels:
        app: site
---
apiVersion: v1
kind: Service
metadata:
  name: site
  namespace: rndir
  labels:
    app: site
spec:
  selector:
    app: site
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
